name: gif-cli
version: 0.0.3
summary: CLI tool to search for gifs
description: |
  CLI tool to search for gifs
confinement: strict
base: core18
grade: stable

apps:
  gif-cli:
    command: usr/bin/python3 -u $SNAP/bin/gif-cli
    plugs: [network-bind, network]

parts:
  gif-cli:
    plugin: python
    source: .
    python-packages:
      - requests
    prime:
      - -install
